### ISSUE TITLE
synchronisation problem

### ISSUE THREAD

**Issue by cchaantaall** [cchaantaall/learn#1]
i cant get the progress app conncted with github so i dont see any progress
@thomasjbradley

**Comment by thomasjbradley** [comment]
Are you getting any error messages?

**Comment by thomasjbradley** [comment]
Could you send me a screenshot of where you mean? Thanks!

**Comment by cchaantaall** [comment]
> 
![afbeelding](https://github.com/cchaantaall/learn/assets/1711392/9b3d5772-e3ec-4856-9698-30dc082289a8)
 i cant select a course here, and if i do some parts of the courses it wont get marked as done

**Comment by cchaantaall** [comment]
![afbeelding](https://github.com/cchaantaall/learn/assets/1711392/a74467ac-c5aa-4acd-af81-aa0417efbc36)
@thomasjbradley  

ive done the lesson multiple times but i dont get a mark

**Comment by thomasjbradley** [comment]
That’s only used if you are a student at Algonquin College & using this system for your grades. The system isn’t currently being used at Algonquin so there are no listed courses online.

You can still use all the features without having a specific course assigned.
